import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import java.net.URL;

public class App extends Application {
    public static void main(String[] args) throws Exception {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        /*
         * Loads the scene generated by SceneBuilder and Generates the main window.
         */
        URL path_view = getClass().getResource("login_view.fxml");
        FXMLLoader loader = new FXMLLoader(path_view);

        Scene scene = new Scene(loader.load());
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
